import random

WORDS = [
{"word":"apple","def":"a round red or green fruit"},
{"word":"table","def":"a piece of furniture with four legs"},
{"word":"river","def":"a natural flowing stream of water"},
{"word":"smile","def":"an expression of happiness"},
{"word":"music","def":"organized sound that is pleasant to hear"},
{"word":"cloud","def":"a visible mass of tiny water drops in the sky"},
{"word":"orange","def":"a citrus fruit and a color"},
{"word":"pencil","def":"a tool for writing or drawing"},
{"word":"window","def":"an opening in a wall that lets in light"},
{"word":"garden","def":"a place where plants and flowers grow"},
{"word":"chair","def":"a seat for one person"},
{"word":"happy","def":"feeling or showing pleasure"},
{"word":"water","def":"a clear liquid essential for life"},
{"word":"map","def":"a drawing of the world or an area"},
{"word":"bread","def":"a baked food made from flour"},
{"word":"light","def":"the natural agent that makes things visible"},
{"word":"book","def":"a set of written or printed pages"},
{"word":"phone","def":"a device for voice communication"},
{"word":"mouse","def":"a small rodent"},
{"word":"green","def":"the color of grass"},
{"word":"family","def":"parents and their children"},
{"word":"friend","def":"a person you like and trust"},
{"word":"school","def":"a place where people learn"},
{"word":"beach","def":"a sandy shore by water"},
{"word":"house","def":"a building for people to live in"},
{"word":"flower","def":"the bloom of a plant"},
{"word":"sunny","def":"bright with sunlight"},
{"word":"coffee","def":"a drink made from roasted beans"},
{"word":"paper","def":"material for writing or printing on"},
{"word":"shirt","def":"a garment for the upper body"},
{"word":"dog","def":"a domestic canine animal"},
{"word":"cat","def":"a small domestic feline"},
{"word":"bird","def":"an animal with feathers and wings"},
{"word":"fish","def":"an aquatic animal with gills"},
{"word":"tree","def":"a tall plant with a trunk"},
{"word":"candy","def":"sweet confectionery"},
{"word":"cookie","def":"a small sweet baked snack"},
{"word":"milk","def":"a white liquid from mammals"},
{"word":"cake","def":"a sweet baked dessert"},
{"word":"cheese","def":"food made from curdled milk"},
{"word":"butter","def":"a solid dairy spread"},
{"word":"clock","def":"a device that shows time"},
{"word":"plane","def":"an aircraft with wings"},
{"word":"train","def":"a connected series of railroad cars"},
{"word":"car","def":"a road vehicle with four wheels"},
{"word":"bike","def":"a two-wheeled vehicle pedaled by the rider"},
{"word":"road","def":"a paved path for vehicles"},
{"word":"city","def":"a large town"},
{"word":"park","def":"public green space for recreation"},
{"word":"game","def":"an activity for fun or competition"},
{"word":"movie","def":"a motion picture"},
{"word":"story","def":"a narrative of events"},
{"word":"lunch","def":"a midday meal"},
{"word":"dinner","def":"an evening meal"},
{"word":"breakfast","def":"a morning meal"},
{"word":"baby","def":"a very young child"},
{"word":"sister","def":"a female sibling"},
{"word":"brother","def":"a male sibling"},
{"word":"mother","def":"a female parent"},
{"word":"father","def":"a male parent"},
{"word":"grandma","def":"your mother’s or father’s mother"},
{"word":"grandpa","def":"your mother’s or father’s father"},
{"word":"rain","def":"water falling from clouds"},
{"word":"snow","def":"frozen water crystals falling from clouds"},
{"word":"wind","def":"moving air"},
{"word":"star","def":"a huge ball of burning gas in space"},
{"word":"moon","def":"Earth’s natural satellite"},
{"word":"sun","def":"the star at the center of our solar system"},
{"word":"space","def":"the region beyond Earth’s atmosphere"},
{"word":"earth","def":"the planet we live on"},
{"word":"fire","def":"combustion producing heat and light"},
{"word":"ice","def":"frozen water"},
{"word":"rock","def":"solid mineral material"},
{"word":"ocean","def":"a vast body of salt water"},
{"word":"lake","def":"a large inland body of water"},
{"word":"hill","def":"a raised area of land"},
{"word":"farm","def":"land used for growing crops or animals"},
{"word":"grass","def":"short green plants covering ground"},
{"word":"ball","def":"a round object used in games"},
{"word":"jump","def":"to push yourself off the ground"},
{"word":"dance","def":"move rhythmically to music"},
{"word":"laugh","def":"express joy with sound"},
{"word":"paint","def":"apply color to a surface"},
{"word":"color","def":"the property of light seen by the eye"},
{"word":"brush","def":"a tool with bristles for painting"},
{"word":"song","def":"a short musical composition"},
{"word":"gift","def":"something given to another"},
{"word":"heart","def":"an organ that pumps blood"},
{"word":"hope","def":"expectation of good"},
{"word":"dream","def":"thoughts during sleep or aspirations"},
{"word":"planet","def":"a large body orbiting a star"},
{"word":"shell","def":"a hard outer covering"},
{"word":"island","def":"land surrounded by water"},
{"word":"leaf","def":"a flat green part of a plant"},
{"word":"arrow","def":"a pointed missile shot from a bow"},
{"word":"sugar","def":"sweet crystalline substance"},
{"word":"salt","def":"a white crystalline seasoning"},
{"word":"banana","def":"a long yellow fruit"},
{"word":"lemon","def":"a sour yellow citrus fruit"},
{"word":"grape","def":"a small round purple or green fruit"},
{"word":"kitten","def":"a young cat"},
{"word":"zephyr","def":"a gentle breeze"},
{"word":"labyrinth","def":"a complex maze"},
{"word":"serendipity","def":"finding good things without looking"},
{"word":"quagmire","def":"a difficult situation"},
{"word":"eloquence","def":"fluent persuasive speaking"},
{"word":"ephemeral","def":"lasting a very short time"},
{"word":"ubiquitous","def":"present everywhere"},
{"word":"paradox","def":"a self-contradictory statement"},
{"word":"juxtapose","def":"to place side by side"},
{"word":"nebulous","def":"vague or unclear"},
{"word":"cacophony","def":"harsh discordant sound"},
{"word":"clandestine","def":"secret or hidden"},
{"word":"ambivalent","def":"having mixed feelings"},
{"word":"dichotomy","def":"a division into two parts"},
{"word":"mellifluous","def":"sweetly flowing sound"},
{"word":"quintessential","def":"the most typical example"},
{"word":"pernicious","def":"harmful in a subtle way"},
{"word":"obstinate","def":"stubbornly refusing to change"},
{"word":"conundrum","def":"a confusing problem"},
{"word":"avarice","def":"extreme greed"},
{"word":"benevolent","def":"kind and generous"},
{"word":"belligerent","def":"hostile and aggressive"},
{"word":"magnanimous","def":"very generous or forgiving"},
{"word":"gregarious","def":"sociable and outgoing"},
{"word":"idiosyncrasy","def":"a peculiar habit"},
{"word":"loquacious","def":"very talkative"},
{"word":"nefarious","def":"wicked or criminal"},
{"word":"obstreperous","def":"noisy and difficult to control"},
{"word":"perspicacious","def":"having keen understanding"},
{"word":"recalcitrant","def":"resisting authority"},
{"word":"sagacious","def":"wise and shrewd"},
{"word":"tenacious","def":"holding firmly"},
{"word":"vacillate","def":"to waver between choices"},
{"word":"voracious","def":"having a huge appetite"},
{"word":"winsome","def":"attractive and charming"},
{"word":"xenophile","def":"one attracted to foreign things"},
{"word":"yearnful","def":"filled with longing"},
{"word":"zealous","def":"showing great energy for a cause"},
{"word":"acrimonious","def":"bitter in tone"},
{"word":"bamboozle","def":"to trick or deceive"},
{"word":"circumspect","def":"careful and cautious"},
{"word":"deleterious","def":"harmful"},
{"word":"ebullient","def":"cheerful and energetic"},
{"word":"fastidious","def":"very attentive to detail"},
{"word":"grandiloquent","def":"pompous in speech"},
{"word":"harbinger","def":"a sign of something to come"},
{"word":"ineffable","def":"too great for words"},
{"word":"judicious","def":"showing good judgment"},
{"word":"knavery","def":"untrustworthy behavior"},
{"word":"lugubrious","def":"sad and dismal"},
{"word":"mawkish","def":"overly sentimental"},
{"word":"nonchalant","def":"calm and relaxed"},
{"word":"obsequious","def":"excessively submissive"},
{"word":"panacea","def":"a universal cure"},
{"word":"querulous","def":"complaining habitually"},
{"word":"rambunctious","def":"wildly energetic"},
{"word":"sanguine","def":"optimistic in bad times"},
{"word":"truculent","def":"eager to fight"},
{"word":"unctuous","def":"excessively flattering"},
{"word":"veracity","def":"truthfulness"},
{"word":"wistful","def":"sadly longing"},
{"word":"xenophobia","def":"fear of foreigners"},
{"word":"yen","def":"a strong desire"},
{"word":"zenith","def":"highest point"},
{"word":"abrogate","def":"to repeal or do away with"},
{"word":"blasphemous","def":"disrespectful toward religion"},
{"word":"capitulate","def":"to surrender"},
{"word":"demagogue","def":"a leader who exploits emotions"},
{"word":"enervate","def":"to weaken"},
{"word":"florid","def":"elaborately decorated"},
{"word":"guile","def":"sly or cunning intelligence"},
{"word":"hegemony","def":"dominant leadership"},
{"word":"impetuous","def":"acting quickly without thought"},
{"word":"kowtow","def":"to act excessively subservient"},
{"word":"laconic","def":"using few words"},
{"word":"myopic","def":"short-sighted"},
{"word":"nadir","def":"lowest point"},
{"word":"onerous","def":"burdensome"},
{"word":"placate","def":"to calm or pacify"},
{"word":"reticent","def":"not revealing thoughts easily"},
{"word":"salient","def":"most noticeable"},
{"word":"taciturn","def":"habitually silent"},
{"word":"umbrage","def":"offense or annoyance"},
{"word":"vanguard","def":"leading position in a movement"},
{"word":"wry","def":"dryly humorous"},
{"word":"yare","def":"ready and quick"},
{"word":"zeitgeist","def":"the spirit of the time"},
{"word":"abstemious","def":"not self-indulgent"},
{"word":"calumny","def":"false statements to harm reputation"},
{"word":"didactic","def":"intended to teach"},
{"word":"effervescent","def":"bubbly and lively"},
{"word":"felicitous","def":"pleasantly appropriate"},
{"word":"glib","def":"smooth but insincere"},
{"word":"hubris","def":"excessive pride"},
{"word":"iconoclast","def":"one who attacks beliefs"},
{"word":"jettison","def":"to throw overboard"},
{"word":"kismet","def":"fate or destiny"},
{"word":"lackadaisical","def":"lacking enthusiasm"},
{"word":"mercurial","def":"subject to sudden change"}
]

def random_word():
    return random.choice(WORDS)
